### PR TITLE
Add a status plot markdown file to conflate plots of all benchmarks

### PR DESCRIPTION
**Pull request by ayaz91**
This is an empty markdown file to collect all status plots for different benchmark suites. Once, completed, I will push it to gem5 webpage/resources.

### CODE REVIEW

**Comment by tv-reddy** [comment]
@ayaz91 should we merge this? so that everyone can work on their copy.

**Comment by ayaz91** [comment]
@tv-reddy : I was expecting that we all will push our changes to the same branch, since we will be modifying the different parts of this file. Does that sound reasonable ?

**Comment by tv-reddy** [comment]
Okay, I will work on this branch. Thanks

**Comment by tv-reddy** [comment]
@ayaz91 @takekoputa should upload status w.r.t gem5-19?

**Comment by ayaz91** [comment]
I think gem5-20 status should be enough for this page.

**Comment by ayaz91** [comment]
@mahyarsamani @marjanfariborz : Just a reminder to please update this branch with any  benchmark status plots you might have. Also, please, update gem5-resources repo with any resources stuff you have (for reference: https://gem5-review.googlesource.com/c/public/gem5-resources/+/29572). We want to have this information uploaded before the workshop (and reviews are going to need some time as well).

**Pull request closed without merging**
